name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ARM_CLIENT_ID: "${{ secrets.CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.CLIENT_SECRET }}"
  # TODO: Move this to secrets
  ARM_SUBSCRIPTION_ID: "271ac31c-4007-444c-a88d-30cd78fa2a03"
  ARM_TENANT_ID: "${{ secrets.TENANT_ID }}"
  ARM_ACCESS_KEY: "${{ secrets.ARM_ACCESS_KEY }}"

jobs:  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
           username: ${{ secrets.ACR_USERNAME }}
           password: ${{ secrets.ACR_PASSWORD }}
           login-server: ${{ secrets.ACR_SERVER }}
       
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: /Dockerfile
          push: true
          tags: frontlineacr.azurecr.io/web:${{ github.run_number }}

  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    environment: Development

    defaults:
      run:
        working-directory: ./src/infra

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
  
      - name: Terraform Workspace
        run: terraform workspace select dev || terraform workspace new dev

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan \
            -var 'container_image_tag=${{ github.run_number }}'

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var 'container_image_tag=${{ github.run_number }}'

  deploy_prod:
    runs-on: ubuntu-latest
    needs: deploy_dev

    environment: Production

    defaults:
      run:
        working-directory: ./src/infra

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
  
      - name: Terraform Workspace
        run: terraform workspace select prod || terraform workspace new prod

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan \
            -var 'container_image_tag=${{ github.run_number }}'

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var 'container_image_tag=${{ github.run_number }}'